/**
 * Created by sahil-dua on 9/5/17.
 */

export const FETCH_USER_STARTED = 'FETCH_USER_STARTED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const CREATE_BUZZ_STARTED = 'CREATE_BUZZ_STARTED';
export const CREATE_BUZZ_SUCCESS = 'CREATE_BUZZ_SUCCESS';
export const CREATE_BUZZ_FAILURE = 'CREATE_BUZZ_FAILURE';
export const FETCH_BUZZ_STARTED = 'FETCH_BUZZ_STARTED';
export const FETCH_BUZZ_SUCCESS = 'FETCH_BUZZ_SUCCESS';
export const FETCH_BUZZ_FAILURE = 'FETCH_BUZZ_FAILURE';
export const LIKE_DISLIKE_STARTED = 'LIKE_DISLIKE_STARTED';
export const LIKE_DISLIKE_SUCCESS = 'LIKE_DISLIKE_SUCCESS';
export const LIKE_DISLIKE_FAILURE = 'LIKE_DISLIKE_FAILURE';
export const CREATE_COMMENT_STARTED = 'CREATE_COMMENT_STARTED';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const FETCH_COMMENTS_STARTED = 'FETCH_COMMENTS_STARTED';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
