/**
 * Created by sahil-dua on 9/5/17.
 */

export const FETCH_USER_STARTED = 'FETCH_USER_STARTED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const CREATE_BUZZ_STARTED = 'CREATE_BUZZ_STARTED';
export const CREATE_BUZZ_SUCCESS = 'CREATE_BUZZ_SUCCESS';
export const CREATE_BUZZ_FAILURE = 'CREATE_BUZZ_FAILURE';